import { Router, type Request, type Response } from 'express';
import { randomBytes } from 'node:crypto';
import sodium from 'libsodium-wrappers';
import { extractOboIdentity } from '../middleware/auth.js';
import { getInstallationToken, getInstallationIdForRepo } from '../github/app-auth.js';
import type { Db } from '../db/index.js';
import type { RepoEntry } from '../db/types.js';

// Encrypt a secret for the GitHub Actions Secrets API using libsodium crypto_box_seal.
// Reference: https://docs.github.com/en/rest/actions/secrets#create-or-update-a-repository-secret
async function encryptSecretForGitHub(repoPublicKeyB64: string, plaintext: string): Promise<string> {
  await sodium.ready;
  const pubKeyBytes = sodium.from_base64(repoPublicKeyB64, sodium.base64_variants.ORIGINAL);
  const msgBytes = sodium.from_string(plaintext);
  const encrypted = sodium.crypto_box_seal(msgBytes, pubKeyBytes);
  return sodium.to_base64(encrypted, sodium.base64_variants.ORIGINAL);
}

async function setRepoSecret(
  owner: string,
  repo: string,
  secretName: string,
  plaintext: string,
  token: string,
): Promise<void> {
  const pkResp = await fetch(
    `https://api.github.com/repos/${owner}/${repo}/actions/secrets/public-key`,
    {
      headers: {
        Authorization: `Bearer ${token}`,
        Accept: 'application/vnd.github+json',
        'X-GitHub-Api-Version': '2022-11-28',
      },
    },
  );
  if (!pkResp.ok) {
    throw new Error(`Failed to fetch public key for ${owner}/${repo}: HTTP ${pkResp.status}`);
  }
  const pkData = await pkResp.json() as { key_id: string; key: string };

  const encryptedValue = await encryptSecretForGitHub(pkData.key, plaintext);

  const putResp = await fetch(
    `https://api.github.com/repos/${owner}/${repo}/actions/secrets/${secretName}`,
    {
      method: 'PUT',
      headers: {
        Authorization: `Bearer ${token}`,
        Accept: 'application/vnd.github+json',
        'X-GitHub-Api-Version': '2022-11-28',
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({ encrypted_value: encryptedValue, key_id: pkData.key_id }),
    },
  );
  if (putResp.status !== 201 && putResp.status !== 204) {
    throw new Error(`Failed to set secret ${secretName} on ${owner}/${repo}: HTTP ${putResp.status}`);
  }
}

function generateCallerStub(_repoHtmlUrl: string): string {
  return `# .github/workflows/hi-genie-relay.yml
# Auto-generated by Hey Isaac / Hi Genie — do not edit by hand.
# Re-register via the owner dashboard to regenerate.
name: Hi Genie Relay

on:
  pull_request:
    types: [opened, closed, synchronize, reopened, review_requested]
  push:
  pull_request_review:
  pull_request_review_comment:
  issues:
    types: [opened, edited, closed, reopened]
  issue_comment:
    types: [created, edited]
  workflow_run:
    types: [completed]
  check_run:
    types: [completed]

jobs:
  relay:
    runs-on: ubuntu-latest
    steps:
      - name: Relay event to Hi Genie
        env:
          HI_GENIE_WEBHOOK_SECRET: \${{ secrets.HI_GENIE_WEBHOOK_SECRET }}
          HI_GENIE_SP_CLIENT_ID: \${{ secrets.HI_GENIE_SP_CLIENT_ID }}
          HI_GENIE_SP_CLIENT_SECRET: \${{ secrets.HI_GENIE_SP_CLIENT_SECRET }}
          HI_GENIE_APP_URL: \${{ secrets.HI_GENIE_APP_URL }}
          GITHUB_EVENT_PAYLOAD: \${{ toJson(github.event) }}
        run: |
          set +e

          # Extract workspace host (protocol://hostname only) from APP_URL
          APP_HOST=$(python3 -c "from urllib.parse import urlparse; u=urlparse('$HI_GENIE_APP_URL'); print(u.scheme + '://' + u.netloc)")

          # Fetch M2M token from Databricks using relay SP credentials
          TOKEN_RESP=$(curl -sf -X POST \\
            "\${APP_HOST}/oidc/v1/token" \\
            -H "Content-Type: application/x-www-form-urlencoded" \\
            -d "grant_type=client_credentials&client_id=\${HI_GENIE_SP_CLIENT_ID}&client_secret=\${HI_GENIE_SP_CLIENT_SECRET}&scope=all-apis" 2>&1 || echo "")

          M2M_TOKEN=$(echo "$TOKEN_RESP" | python3 -c "import json,sys; d=json.load(sys.stdin); print(d.get('access_token',''))" 2>/dev/null || echo "")
          if [ -z "$M2M_TOKEN" ]; then
            echo "::warning::relay failed: could not obtain M2M token"
            exit 0
          fi

          # Re-serialize payload (matches JSON.stringify byte-for-byte)
          PAYLOAD=$(python3 -c "
import json, sys
data = json.loads(sys.stdin.read())
print(json.dumps(data, separators=(',', ':')), end='')
" <<< "$GITHUB_EVENT_PAYLOAD")

          # HMAC-sign the canonical payload
          SIG=$(python3 -c "
import hmac, hashlib, sys
secret = sys.argv[1].encode()
payload = sys.argv[2].encode()
print('sha256=' + hmac.new(secret, payload, hashlib.sha256).hexdigest())
" "$HI_GENIE_WEBHOOK_SECRET" "$PAYLOAD")

          # POST to Hi Genie
          HTTP_STATUS=$(curl -s -o /dev/null -w "%{http_code}" -X POST \\
            "\${HI_GENIE_APP_URL}/webhook/github" \\
            -H "Content-Type: application/json" \\
            -H "X-Hub-Signature-256: \${SIG}" \\
            -H "X-GitHub-Event: \${{ github.event_name }}" \\
            -H "Authorization: Bearer \${M2M_TOKEN}" \\
            -d "\${PAYLOAD}")

          if [ "$HTTP_STATUS" -lt 200 ] || [ "$HTTP_STATUS" -ge 300 ]; then
            echo "::warning::relay failed: \${HTTP_STATUS}"
          fi

          exit 0
`;
}

export function reposRouter(db: Db): Router {
  const router = Router();

  router.use((req, res, next) => {
    if (!extractOboIdentity(req)) {
      return res.status(401).json({ error: 'unauthenticated' });
    }
    return next();
  });

  /**
   * GET /api/repos/status?project_id=<uuid>
   * Returns repo_config rows + last PR delivery timestamp for each repo.
   */
  router.get('/status', async (req, res) => {
    const { project_id } = req.query as { project_id?: string };
    if (!project_id) return res.status(400).json({ error: 'project_id required' });

    try {
      const row = await db.query(
        `SELECT repos, updated_at FROM app.repo_config WHERE project_id = $1`,
        [project_id],
      );
      if (!row.rows.length) return res.json({ repos: [] });

      const repos: RepoEntry[] = row.rows[0].repos ?? [];
      // Enrich with last PR delivery
      const enriched = await Promise.all(
        repos.map(async (r) => {
          const pr = await db.query(
            `SELECT created_at FROM app.pull_requests WHERE repo_url = $1 ORDER BY created_at DESC LIMIT 1`,
            [r.url],
          );
          return {
            url: r.url,
            installation_id: r.installation_id ?? null,
            last_delivery: pr.rows[0]?.created_at ?? null,
          };
        }),
      );
      return res.json({ repos: enriched });
    } catch (err) {
      console.error('[repos] status error:', err);
      return res.status(500).json({ error: 'internal_error' });
    }
  });

  /**
   * POST /api/repos/preflight
   * Body: { project_id, repo: "owner/name" }
   * Returns what actions will be taken without executing them.
   */
  router.post('/preflight', async (req, res) => {
    const { project_id, repo } = req.body as { project_id: string; repo: string };
    if (!project_id || !repo) return res.status(400).json({ error: 'project_id and repo required' });

    const [owner, repoName] = repo.split('/');
    if (!owner || !repoName) return res.status(400).json({ error: 'repo must be in owner/name format' });

    try {
      let token: string | null = null;
      let appInstalled = true;
      try {
        const installationId = await getInstallationIdForRepo(owner, repoName);
        token = await getInstallationToken(installationId);
      } catch {
        appInstalled = false;
      }

      let workflowExists = false;
      if (token) {
        const wfResp = await fetch(
          `https://api.github.com/repos/${repo}/contents/.github/workflows/hi-genie-relay.yml`,
          {
            headers: {
              Authorization: `Bearer ${token}`,
              Accept: 'application/vnd.github+json',
              'X-GitHub-Api-Version': '2022-11-28',
            },
          },
        );
        workflowExists = wfResp.ok;
      }

      return res.json({
        app_installed: appInstalled,
        install_url: appInstalled ? null : `https://github.com/apps/hey-isaac-hi-genie/installations/new`,
        actions: [
          { name: 'Set HI_GENIE_WEBHOOK_SECRET secret', status: 'will_create' },
          { name: 'Commit hi-genie-relay.yml workflow', status: workflowExists ? 'will_update' : 'will_create' },
          { name: 'Update repo_config', status: 'will_upsert' },
        ],
      });
    } catch (err) {
      console.error('[repos] preflight error:', err);
      return res.status(500).json({ error: 'internal_error' });
    }
  });

  /**
   * POST /api/repos/register
   * Body: { project_id, repo: "owner/name" }
   * Performs all registration steps atomically (best-effort per step).
   */
  router.post('/register', async (req: Request, res: Response) => {
    const { project_id, repo } = req.body as { project_id?: string; repo?: string };
    if (!project_id || !repo) {
      res.status(400).json({ error: 'project_id and repo required' });
      return;
    }

    const [owner, repoName] = repo.split('/');
    if (!owner || !repoName) {
      res.status(400).json({ error: 'repo must be in owner/name format' });
      return;
    }
    const repoHtmlUrl = `https://github.com/${owner}/${repoName}`;

    // Relay SP env vars must be present before we touch GitHub
    const relaySPClientId = process.env.RELAY_SP_CLIENT_ID?.trim();
    const relaySPClientSecret = process.env.RELAY_SP_CLIENT_SECRET?.trim();
    const appPublicUrl = process.env.APP_PUBLIC_URL?.trim();
    if (!relaySPClientId || !relaySPClientSecret || !appPublicUrl) {
      res.status(503).json({
        error: 'relay_sp_not_configured',
        message: 'Run provision_relay_spn setup job first',
      });
      return;
    }

    const steps: Array<{ name: string; status: 'ok' | 'error'; detail?: string }> = [];

    let installationId: number;
    try {
      installationId = await getInstallationIdForRepo(owner, repoName);
    } catch {
      res.status(409).json({
        error: 'app_not_installed',
        install_url: `https://github.com/apps/hey-isaac-hi-genie/installations/new`,
        message: `GitHub App is not installed on ${repo}. Install it first.`,
      });
      return;
    }
    steps.push({ name: 'Verify GitHub App installation', status: 'ok' });

    let installToken: string;
    try {
      installToken = await getInstallationToken(installationId);
    } catch (err) {
      res.status(502).json({ error: `github_token_failed: ${(err as Error).message}` });
      return;
    }

    const perRepoWebhookSecret = randomBytes(32).toString('hex');
    const secretsToSet = [
      { name: 'HI_GENIE_WEBHOOK_SECRET', value: perRepoWebhookSecret },
      { name: 'HI_GENIE_SP_CLIENT_ID', value: relaySPClientId },
      { name: 'HI_GENIE_SP_CLIENT_SECRET', value: relaySPClientSecret },
      { name: 'HI_GENIE_APP_URL', value: appPublicUrl },
    ];

    try {
      for (const { name, value } of secretsToSet) {
        await setRepoSecret(owner, repoName, name, value, installToken);
      }
      steps.push({ name: 'Set Actions secrets', status: 'ok' });

      const workflowContent = generateCallerStub(repoHtmlUrl);
      const workflowB64 = Buffer.from(workflowContent, 'utf8').toString('base64');

      // Check for existing file (need SHA to update)
      const existResp = await fetch(
        `https://api.github.com/repos/${repo}/contents/.github/workflows/hi-genie-relay.yml`,
        {
          headers: {
            Authorization: `Bearer ${installToken}`,
            Accept: 'application/vnd.github+json',
            'X-GitHub-Api-Version': '2022-11-28',
          },
        },
      );
      const existingData = existResp.ok ? await existResp.json() as { sha: string } : null;

      const putBody: Record<string, string> = {
        message: 'chore: add Hi-Genie event relay workflow',
        content: workflowB64,
      };
      if (existingData?.sha) putBody.sha = existingData.sha;

      const putResp = await fetch(
        `https://api.github.com/repos/${repo}/contents/.github/workflows/hi-genie-relay.yml`,
        {
          method: 'PUT',
          headers: {
            Authorization: `Bearer ${installToken}`,
            Accept: 'application/vnd.github+json',
            'X-GitHub-Api-Version': '2022-11-28',
            'Content-Type': 'application/json',
          },
          body: JSON.stringify(putBody),
        },
      );
      if (!putResp.ok) {
        const errBody = await putResp.text();
        throw new Error(`Workflow commit failed: ${putResp.status} ${errBody}`);
      }
      steps.push({ name: 'Commit hi-genie-relay.yml workflow', status: 'ok' });

      const repoEntry: RepoEntry = {
        url: repoHtmlUrl,
        webhook_secret: perRepoWebhookSecret,
        installation_id: installationId,
      };
      const repoEntryJson = JSON.stringify(repoEntry);
      const updatedBy = (req.user ?? extractOboIdentity(req) ?? 'system').toLowerCase();

      const existingResult = await db.query<{ project_id: string }>(
        `SELECT project_id FROM app.repo_config WHERE project_id = $1`,
        [project_id],
      );

      if (existingResult.rowCount && existingResult.rowCount > 0) {
        // Replace existing entry for this URL, or append if not found
        await db.query(
          `UPDATE app.repo_config
           SET repos = (
             SELECT CASE
               WHEN bool_or(elem->>'url' = $1)
               THEN jsonb_agg(
                 CASE WHEN elem->>'url' = $1 THEN $2::jsonb ELSE elem END
               )
               ELSE repos || jsonb_build_array($2::jsonb)
             END
             FROM jsonb_array_elements(repos) AS elem
           ),
           updated_at = now(),
           updated_by  = $3
           WHERE project_id = $4`,
          [repoHtmlUrl, repoEntryJson, updatedBy, project_id],
        );
      } else {
        await db.query(
          `INSERT INTO app.repo_config (project_id, repos, updated_at, updated_by)
           VALUES ($1, $2::jsonb, now(), $3)`,
          [project_id, JSON.stringify([repoEntry]), updatedBy],
        );
      }
      steps.push({ name: 'Update repo_config', status: 'ok' });

      return res.json({
        ok: true,
        steps,
        installation_id: installationId,
        caller_stub_yaml: generateCallerStub(repoHtmlUrl),
        relay: { status: 'pending' },
      });
    } catch (err) {
      console.error('[repos] register error:', err);
      const message = err instanceof Error ? err.message : String(err);
      steps.push({ name: 'Registration failed', status: 'error', detail: message });
      return res.status(500).json({ ok: false, steps, error: message });
    }
  });

  return router;
}
